#! /usr/bin/env bash

# Create a usable starter meta.json,
# with a link to the tracked file,
# and a link to the resulting meta.json.
# https://github.com/a3n/miki

set -o errexit # Exit with error: any error.
set -o nounset # Exit with error: an unset env variable is used.

[ -d "$MWK" ] || (
    echo "$0: Required: export MWK=~/top/directory/of/your/wiki"
    echo "\$MWK = \"$MWK\""
    exit 1
)

# Don't overwrite existing meta.json.
[ -e meta.json ] && echo "ERROR: meta.json already exists." && exit 1

# File to link to is the only allowed argument.
[ $# != 1 ] && echo "ERROR: Exactly 1 link argument allowed." && exit 2

here=$(pwd)
expandedLink=$MWK${here#$MWK}/$1
link=\$MWK${here#$MWK}/$1
meta=\$MWK${here#$MWK}/meta.json

[ ! -e $expandedLink ] && echo "WARNING: $link not found. meta.json written anyway."

touch meta.json
cat <<EOF >meta.json
{
    "title": "$1",
    "subtitle": "$1",
    "categoryPrimary": "none",
    "categorySecondary": "none",
    "link": "$link",
    "note": "Edit all fields except link and meta.",
    "meta": "$meta"
}
EOF
